### ISSUE TITLE
Use yarn to speed up builds and use cache feature on Travis CI

### ISSUE THREAD

**Issue by verzola** [catho/spalatum#10]
Is there any reason to not use yarn to manage dependencies?
It is faster than npm and it can be easily cached on Travis CI to speed up builds:
https://docs.travis-ci.com/user/caching/#yarn-cache

The difference seems to be reasonable:
![screenshot from 2018-04-07 16-07-27](https://user-images.githubusercontent.com/2985522/38459247-d32fbc1c-3a7d-11e8-9213-ec2bf06bd938.png)

5.256s NPM **vs** 1.98s YARN -> almost three times faster

**Comment by luizdesign** [comment]
Fixed on #18
